### ISSUE TITLE
Question: GraphQL ? 

### ISSUE THREAD

**Issue by airtonix** [NimitzDEV/nestjs-electron-ipc-transport#1]
I checked out your example repo, and got it up and running.

![image](https://user-images.githubusercontent.com/61225/129428700-de2b11ab-aec4-4f3c-a3df-d0e11ed34063.png)

It's obvious, with your Aspect Orientated decorators that this is more appropriate for a Restful API approach? 

But i'd like to use GraphQL instead, So from what I can see, making this work for GraphQL would not require the message handling AOP approach you have, and instead find a way to pass it straight up to the nestjs apollo server.

**Comment by NimitzDEV** [comment]
Hi, NestJS have an out-of-box solution for GraphQL, I think you can use that directly without any issues and won't require any message handling.  You could run an internal GraphQL server in the main process for your app in the renderer process, and inject your port number to renderer, and connect to it, then it will work perfectly. 🍺
