### ISSUE TITLE
Correct usage ?

### ISSUE THREAD

**Issue by dirodriguezm** [NimitzDEV/nestjs-electron-ipc-transport#2]
Hi @NimitzDEV, I want to thank you for making this package. It is very useful and a great inspiration.

I was thinking that I probably don't want to create the NestJS application inside the main process of Electron. Wouldn't it be more correct to create a fork process that runs NestJS ? Or for development purposes, having two renderer processes (windows), one with the frontend and another with the NestJS app.

In that case how would you aproach the creation of a fork process that runs the Nest application ? I'm having trouble differentiating the Electron instantiation with the Nest app and the Webpack app.

PS: I reposted this issue from the example repo, but made more sense to post here.

**Comment by NimitzDEV** [comment]
Hello @dirodriguezm , thanks for using this package. So the purpose of this package is to provide the ability to develop Electron applications within NestJS framework. And this package turns NestJS into the main backend for your Electron app and handling IPC messaging via decorators. So in my opinion, you do not need to create a separate process for NestJS.
So, with this package, the webpack app is just a regular front-end project, and the Nest app is your main process now.

**Comment by dirodriguezm** [comment]
Thanks for your response. I see what you mean, but isn't it better to not have the main process as the backend ?

Say for example that you have a big computation on NestJS. If you block electron's main process then the app becomes unresponsive. If the computation is on a different process then electron's main process is free. 

How does this package deal with stuff like this ?

**Comment by NimitzDEV** [comment]
Hello, so from my experience, we will put those CPU-intensive tasks into a separate process, rather than putting the whole backend into a separate process. This package is most suitable for regular Electron tasks like creating a new window, handling login, etc.
